name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test
        setup-command: ''
        command: javac LinkedList.java && java LinkedList
        input: |-
          1
          2
          3
          null
        expected-output: |-
          Enter integers to create nodes (enter a non-integer to exit):
          Linked List created
          Linked List Before Deleting
          1 -> 2 -> 3 -> null
          Deletion at Tail
          Deleted Element is:3
          Linked List After Deleting at tail
          1 -> 2 -> null
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
